# Generated by Django 3.0.8 on 2020-08-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appfolio.PostCategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
    ]
