# Generated by Django 3.0.8 on 2020-08-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfolio', '0002_auto_20200820_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
    ]
