# Generated by Django 3.0.8 on 2020-08-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfolio', '0003_post_abstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='abstract',
            new_name='goalText',
        ),
        migrations.AddField(
            model_name='post',
            name='goal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='languages',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='languagesText',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='softwares',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='softwaresText',
            field=models.TextField(blank=True),
        ),
    ]
